# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BellSchedule', '0002_auto_20161004_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdays',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialdays',
            name='keep_normal_rotation',
            field=models.BooleanField(default=False, verbose_name='Keep Normal Rotation'),
        ),
        migrations.AlterField(
            model_name='yearcalendar',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Schedule Name'),
        ),
    ]
