# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BellSchedule', '0003_auto_20161004_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyBells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Bell Name')),
                ('active', models.BooleanField(default=False)),
                ('ring_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BellSchedule.RingPattern')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyDrills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Bell Name')),
                ('date', models.DateField()),
                ('time', models.TimeField(verbose_name='Ring Time')),
                ('emergency_bell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BellSchedule.EmergencyBells')),
            ],
        ),
    ]
