# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BellSchedule', '0004_emergencybells_emergencydrills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bell',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Bell Name'),
        ),
        migrations.AlterField(
            model_name='emergencybells',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Bell Name'),
        ),
        migrations.AlterField(
            model_name='emergencydrills',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Bell Name'),
        ),
        migrations.AlterField(
            model_name='ringpattern',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Ring Pattern Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Schedule Name'),
        ),
    ]
