# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BellSchedule', '0005_auto_20161005_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergencyBells',
            new_name='EmergencyBell',
        ),
        migrations.RenameModel(
            old_name='EmergencyDrills',
            new_name='EmergencyDrill',
        ),
        migrations.RenameModel(
            old_name='SpecialDays',
            new_name='SpecialDay',
        ),
    ]
