# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BellSchedule', '0006_auto_20161014_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('stop_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('all_clear_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Emergency Type Name')),
                ('ring_pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BellSchedule.RingPattern')),
            ],
        ),
        migrations.DeleteModel(
            name='Bell',
        ),
        migrations.RemoveField(
            model_name='emergencybell',
            name='ring_pattern',
        ),
        migrations.RemoveField(
            model_name='emergencydrill',
            name='emergency_bell',
        ),
        migrations.DeleteModel(
            name='EmergencyBell',
        ),
        migrations.DeleteModel(
            name='EmergencyDrill',
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='emergency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BellSchedule.EmergencyTypes'),
        ),
    ]
