# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BellSchedule', '0007_auto_20161015_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergencyTypes',
            new_name='EmergencyType',
        ),
    ]
