# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BellSchedule', '0008_auto_20161015_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencytype',
            name='all_clear_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_clear_pattern', to='BellSchedule.RingPattern'),
        ),
        migrations.AlterField(
            model_name='emergencytype',
            name='ring_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ring_pattern', to='BellSchedule.RingPattern'),
        ),
    ]
